/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

let awsmobile;

// Alpha
awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",

    "aws_appsync_apiKey": `${process.env.REACT_APP_APIKEY}`,
    "aws_appsync_graphqlEndpoint": `${process.env.REACT_APP_APPSYNC_ENDPOINT}`,
};

export default awsmobile;